name: Build depends

on:
  workflow_call:
    inputs:
      build-target:
        description: "Target name as defined by matrix.sh"
        required: true
        type: string
      container-path:
        description: "Path to built container at registry"
        required: true
        type: string
      host:
        description: "Target triplet"
        required: true
        type: string

jobs:
  build-depends:
    name: Build depends
    runs-on: ubuntu-22.04
    container:
      image: ${{ inputs.container-path }}
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Cache depends sources
        uses: actions/cache@v4
        with:
          path: |
            depends/sources
          key: depends-sources-${{ hashFiles('depends/packages/*') }}
          restore-keys: |
            depends-sources-${{ hashFiles('depends/packages/*') }}
            depends-sources-

      - name: Cache depends
        uses: actions/cache@v4
        with:
          path: |
            depends/built
            depends/${{ inputs.host }}
          key: ${{ runner.os }}-depends-${{ inputs.build-target }}-${{ hashFiles('depends/packages/*') }}
          restore-keys: |
            ${{ runner.os }}-depends-${{ inputs.build-target }}-${{ hashFiles('depends/packages/*') }}
            ${{ runner.os }}-depends-${{ inputs.build-target }}

      - name: Build depends
        run: env HOST=${{ inputs.host }} make -j$(nproc) -C depends
