name: CI

on:
  push:
  pull_request_target:

permissions:
  contents: read
  packages: write

env:
  DOCKER_DRIVER: overlay2
  FAST_MODE: false

jobs:
  container:
    name: Build container
    uses: ./.github/workflows/build-container.yml

  build-depends:
    name: Build depends
    uses: ./.github/workflows/build-depends.yml
    needs: [container]
    strategy:
      fail-fast: false
      matrix:
        include:
        - build-target: arm-linux
          host: arm-linux-gnueabihf
        - build-target: linux64
          host: x86_64-pc-linux-gnu
        - build-target: win64
          host: x86_64-w64-mingw32
    with:
      build-target:  ${{ matrix.build-target }}
      container-path: ${{ needs.container.outputs.path }}
      host: ${{ matrix.host }}

  build-src:
    name: Build source
    uses: ./.github/workflows/build-src.yml
    needs: [container, build-depends]
    strategy:
      fail-fast: false
      matrix:
        include:
          - build-target: arm-linux
            depends-target: arm-linux
            host: arm-linux-gnueabihf
          - build-target: linux64
            depends-target: linux64
            host: x86_64-pc-linux-gnu
          - build-target: linux64_cxx20
            depends-target: linux64
            host: x86_64-pc-linux-gnu
          - build-target: linux64_fuzz
            depends-target: linux64
            host: x86_64-pc-linux-gnu
          - build-target: linux64_nowallet
            depends-target: linux64
            host: x86_64-pc-linux-gnu
          - build-target: linux64_sqlite
            depends-target: linux64
            host: x86_64-pc-linux-gnu
          - build-target: linux64_tsan
            depends-target: linux64
            host: x86_64-pc-linux-gnu
          - build-target: linux64_ubsan
            depends-target: linux64
            host: x86_64-pc-linux-gnu
          - build-target: win64
            depends-target: win64
            host: x86_64-w64-mingw32
    with:
      build-target:  ${{ matrix.build-target }}
      container-path: ${{ needs.container.outputs.path }}
      depends-target:  ${{ matrix.build-target }}
      host: ${{ matrix.host }}
