name: confliact
on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            // Get a list of all issues
            // See: https://octokit.github.io/rest.js/#pagination
            const opts = github.rest.issues.listForRepo.endpoint.merge({
              ...context.issue,
              pulls: true,
              state: 'open'
            })
            const issues = await github.paginate(opts)

            for (const issue of issues) {
              // console.log("issue: " + JSON.stringify(issue))
              console.log("pull_request: " + issue.number)
              const listFilesOptions = github.rest.pulls.listFiles.endpoint.merge({
                ...context.issue,
                pull_number: issue.number,
              })

              const listFilesResponse = await github.paginate(listFilesOptions)
              const changedFiles = listFilesResponse.map(getFilename)

              console.log("found changed files:")
              for (const file of changedFiles) {
                console.log("  " + file)
              }

              const { data: pullRequest } = await github.rest.pulls.get({
                ...context.issue,
                pull_number: issue.number,
              })
              // console.log("pr: " + JSON.stringify(pullRequest))

              for (const issue2 of issues) {
                if (issue.number == issue2.number) {
                  continue
                }

                // console.log("issue2: " + JSON.stringify(issue2))
                console.log("pull_request2: " + issue2.number)
                const listFilesOptions2 = github.rest.pulls.listFiles.endpoint.merge({
                  ...context.issue,
                  pull_number: issue2.number,
                })

                const listFilesResponse2 = await github.paginate(listFilesOptions2)
                const changedFiles2 = listFilesResponse2.map(getFilename)

                console.log("found changed files:")
                for (const file2 of changedFiles2) {
                  console.log("  " + file2)
                }

                const { data: pullRequest2 } = await github.rest.pulls.get({
                  ...context.issue,
                  pull_number: issue2.number,
                })
                // console.log("pr2: " + JSON.stringify(pullRequest2))

                if (changedFiles2.filter(function(el) {
                    return changedFiles.indexOf(el) >= 0
                }).length > 0) {
                  console.log(issue.number + " conflicts with " + issue2.number)
                  // TODO: fetch and check magic url
                  const magic_url = "https://github.com/${context.issue.owner}/${context.issue.repo}/branches/pre_mergeable/${pullRequest.head.label}...${pullRequest2.head.label}"
                  console.log(magic_url)
                  const result = await github.request(magic_url)
                  console.log(result)
                }
              }
            }

            function getFilename(item) {
              // console.log("item  " + JSON.stringify(item))
              return item.filename
            }
