name: conflibot
on: [push, pull_request]

permissions:
  contents: read
  pull-requests: write
  # Enforce other not needed permissions are off
  actions: none
  checks: none
  deployments: none
  issues: none
  #metadata: read
  packages: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  conflibot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Warn potential conflicts
        uses: udjinm6/conflibot@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
