name: confliact
on: [pull_request]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            // Get a list of all issues
            // See: https://octokit.github.io/rest.js/#pagination
            const opts = github.rest.issues.listForRepo.endpoint.merge({
              ...context.issue,
              state: 'open'
            })
            const issues = await github.paginate(opts)

            for (const issue of issues) {
              if (!issue.pull_request) {
                continue
              }

              // console.log("issue: " + JSON.stringify(issue))
              console.log("pull_request: " + issue.number)
              const listFilesOptions = github.rest.pulls.listFiles.endpoint.merge({
                ...context.issue,
                pull_number: issue.number,
              })

              const listFilesResponse = await github.paginate(listFilesOptions)
              const changedFiles = listFilesResponse.map(getFilename)

              console.log("found changed files:")
              for (const file of changedFiles) {
                console.log("  " + file)
              }
              for (const issue2 of issues) {
                if (!issue2.pull_request || issue.number == issue2.number) {
                  continue
                }

                // console.log("issue2: " + JSON.stringify(issue2))
                console.log("pull_request2: " + issue2.number)
                const listFilesOptions2 = github.rest.pulls.listFiles.endpoint.merge({
                  ...context.issue,
                  pull_number: issue2.number,
                })

                const listFilesResponse2 = await github.paginate(listFilesOptions2)
                const changedFiles2 = listFilesResponse2.map(getFilename)

                console.log("found changed files:")
                for (const file2 of changedFiles2) {
                  console.log("  " + file2)
                }
                if (listFilesResponse2.filter(function(el) {
                    return listFilesResponse.indexOf(el) >= 0
                }).length > 0) {
                  console.log(issue.number + " conflicts with " + issue2.number)
                }
              }
            }

            function getFilename(item) {
              // console.log("item  " + JSON.stringify(item))
              return item.filename
            }

  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            const diff_url = context.payload.pull_request.diff_url
            const result = await github.request(diff_url)
            console.log(result)
