name: Lint

on:
  workflow_call:
    inputs:
      container-path:
        description: "Path to built container at registry"
        required: true
        type: string

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-24.04
    container:
      image: ${{ inputs.container-path }}
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 50

      - name: Initial setup
        run: |
          git config --global --add safe.directory "$PWD"
          git fetch -fu origin develop:develop
        shell: bash

      - name: Run linters
        run: |
          export BUILD_TARGET="linux64"
          export CHECK_DOC=1
          if [ "${{ github.event_name }}" = "pull_request_target" ]; then
            export COMMIT_RANGE="$(git merge-base origin/develop HEAD)..HEAD"
            export PULL_REQUEST="true"
          else
            export COMMIT_RANGE="SKIP_EMPTY_NOT_A_PR"
            export PULL_REQUEST="false"
          fi
          echo "COMMIT_RANGE=${COMMIT_RANGE}"
          ./ci/dash/lint.sh
        shell: bash